import Head from "next/head";
import styles from "../styles/layout.module.css";
import Cart from "./cart";
import Menu from "./menu";

export default function Layout({children, title}){
    return(
        <div>
            <Head>
        <title>Market App {title ? `🛒 ${title}` : ""}</title> // si tengo titulo imprimitelo, si no imprime nada
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu/>
      <div className={styles.container}>
        {children}
      </div>
      <Cart />
        </div>
    )
}